### ISSUE TITLE
version vs onosVersion

### ISSUE THREAD

**Issue by tomikazi** [onosproject/app-registry#3]
I’d like to make a suggestion for the JSON structure. Under each version of the app, the field version refers to the ONOS version with which this version of the app is compatible so perhaps we should change the field to be `onosVersion`.

Also, the query `version` parameter should be applied to filter on the `onosVersion` rather than the application `version`.

**Comment by antonjlin** [comment]
Will amend in next push

**Comment by antonjlin** [comment]
https://github.com/onosproject/app-registry/pull/7

Fixed in PR7
